spring:
    config:
        activate:
            on-profile: "prod"
build:
    version: "v2"

accounts:
    message: "Welcome to EazyBank accounts related local APIs finaltestbro"
    contactDetails:
        name: "Amaal Grega - Production Developer"
        email: "{cipher}5ec47fa759fb7d1d2164e0586814069c6d448fd63bede3b2c1acf0c05235d62debb1878c754e27cf3aafcdc12cd8035a"
    onCallSupport:
        - (452) 456-2176
        - (546) 764-8934
