spring:
    config:
        activate:
            on-profile: "qa"
build:
    version: "v3"
accounts:
    message: "Welcome to EazyBank accounts related local APIs with git sync"
    contactDetails:
        name: "Amaal Grega - QA Developer"
        email: "amaal@eazybank.com"
    onCallSupport:
        - (452) 456-2176
        - (546) 764-8934
