spring:
    config:
        activate:
            on-profile: "qa"
build:
    version: "v2"

card:
    message: "Welcome to EazyBank card related local APIs cloud bus"
    contactDetails:
        name: "Dragos Lech - QA Analyst"
        email: "dragos@eazybank.com"
    onCallSupport:
        - (313) 31-1343
        - (313) 31-1323
