spring:
    config:
        activate:
            on-profile: "prod"
build:
    version: "v2"

loans:
    message: "Welcome to EazyBank loans related local APIs cloud bus"
    contactDetails:
        name: "Amaal Grega - Production Developer"
        email: "amaal@eazybank.com"
    onCallSupport:
        - (452) 456-2176
        - (546) 764-8934
